# Generated by Django 5.0.2 on 2024-02-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParadigmServer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
